spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cliniccore
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: cliniccore-api

server:
  port: 8080
